### ISSUE TITLE
При первом открытии проекта приложение падает

### ISSUE THREAD

**Issue by ETelyatnikova** [yetanothervan/conspector#6]
Шаги:
1) Установить приложение
2) Открыть WinShell
3) Создать папку проекта (в ОС)
4) В приложении выбрать пункт Главного меню "File -> Open folder"
ОР: Открывается папка проекта в окне source
ФР: приложение закрывается

**Comment by ETelyatnikova** [comment]
ошибка в логе:
Application: WinShell.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Project.Models.Project.GetItems(Interfaces.Services.Project.TagTarget, System.Nullable`1<System.Guid>)
   at SourcesManager.TagManagerMain.TagManagerMainVM.ReloadProjectNodes()
   at SourcesManager.ViewBase.ViewBase+<WaitForMyViecThen>d__5.MoveNext()
